### ISSUE TITLE
Hello. i would like to contribute to translate to SPANISH, is it posible ?

### ISSUE THREAD

**Issue by sinfocomp** [LightBurnSoftware/deployment#1]

**Comment by LightBurnSoftware** [comment]
LightBurn is already translated to Spanish - do you mean the software, or the documentation?

**Comment by sinfocomp** [comment]
there are still some dialogs not translated and also some terms used
incorrectly, dicumentation would take some time but yes, i can work on it
too, i build custom laser and plasma machines, it would be nice if you
coild support my plasma machine, it is grbl based, but requires certain
commands before cutting to probe and set torch offset at each pierce, could
we do some arrngements for licencing ?
