### ISSUE TITLE
Any special setting in wifi.txt to allow hidden SSID for lightbridge?

### ISSUE THREAD

**Issue by jensenkd** [LightBurnSoftware/deployment#4]
In the past when i've configured the raspberry pi, i've had to add scan_ssid=1

![image](https://user-images.githubusercontent.com/170765/144547136-7cb4c72a-7bd9-4b71-b3de-302d0d1a06b2.png)

**Comment by adammhaile** [comment]
@jensenkd We don't use wpa_supplicant on the Bridge and instead use NetworkManager. Currently hidden SSIDs are not supported directly - the only way to do so is to use `nmcli` on the Pi itself but be aware that if you get anything wrong there it might screw up the connection between the Pi and your Ruida.
If you need anything else in the future, please reach out on our forum :) https://forum.lightburnsoftware.com/
